steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
    - 'run'
    - 'deploy'
    - 'my-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--memory'
    - '2Gi'
    - '--port'
    - '3000'
    - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'
